adjust reboot and misc

diff --git a/usr/local/sbin/rebootsystemdboot b/usr/local/sbin/rebootsystemdboot
--- a/usr/local/sbin/rebootsystemdboot
+++ b/usr/local/sbin/rebootsystemdboot
@@ -1,11 +1,43 @@
 #!/usr/bin/env bash
 
-efibootmgr --bootnext "$(efibootmgr | grep "Linux Boot Manager" | cut -f1 -d'*' | cut -f2 -d't')"
+main() {
+	declare command="$1"
+	# valid: bootctl list | grep "id: " | cut -f2 -d':' | cut -f2 -d' '
+	local target time skip_reboot
+	target=""
+	time="0"
+	case "${command}" in
+		"systemdboot"|"")
+			time="60"
+			;;
+		"arch"|"arch-fallback"|"arch-lts"|"arch-lts-fallback"|"arch-without-extras")
+			target="${command}"
+			;;
+		"bios")
+			target="auto-reboot-to-firmware-setup"
+			;;
+		"rEFInd"|"refind")
+			target="rEFInd"
+			;;
+		"reset-timeout")
+			time="0"
+			skip_reboot="yes"
+			;;
+		*)
+			echo "Invalid Argument."
+			exit 1
+			;;
+	esac
 
-#efivar --list | grep LoaderConfigTimeout | xargs -l1 efivar -p -n
-#efivar --list | grep LoaderEntryDefault | xargs -l1 efivar -p -n
+	# efivar --list | grep Loader | xargs -l1 efivar -p -n
+	# efivar -n 4a67b082-0a4c-41cf-b6c7-440b29bb8c4f-LoaderConfigTimeout -w -f "/root/efivars/LoaderConfigTimeout-${time}" # Not working.
 
-efivar -n 4a67b082-0a4c-41cf-b6c7-440b29bb8c4f-LoaderConfigTimeout -w -f /root/efivars/LoaderConfigTimeout-60
-efivar -n 4a67b082-0a4c-41cf-b6c7-440b29bb8c4f-LoaderEntryDefault -w -f /root/efivars/LoaderEntryDefault-Arch
+	sed -i "s/^timeout\t[0-9]*\$/timeout\t${time}/g" /boot/loader/loader.conf
+	bootctl set-oneshot "${target}"
 
-systemctl reboot
+	if [[ -z "${skip_reboot}" ]]; then
+		/usr/local/sbin/reboot_into "Linux Boot Manager"
+	fi
+}
+
+main $@
